version: '3'

services:

  web:
    image: 'cubeghost/tagreplacer:latest'
    volumes:
      - /home/.env:/usr/src/app/.env
    expose:
      - "4000"
    environment:
      - NODE_ENV=production
      - PROTOCOL=https
      - HOSTNAME=142.93.67.26
    command: npm run start
