version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
    expose:
      - "4000"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports: 
      - 6379:6739
