version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PROTOCOL=http
      - HOSTNAME=localhost:4000
    depends_on:
        - redis
    command: npm run watch

  redis:
    image: redis
    ports: 
      - 6379:6739
