version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - PROTOCOL=http
      - HOSTNAME=192.168.99.100:4000
    command: npm run watch

